// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto_defs.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Local definitions matching go-quai proto structures
type ProtoHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoHash) Reset() {
	*x = ProtoHash{}
	mi := &file_proto_defs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoHash) ProtoMessage() {}

func (x *ProtoHash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoHash.ProtoReflect.Descriptor instead.
func (*ProtoHash) Descriptor() ([]byte, []int) {
	return file_proto_defs_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoHash) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProtoAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoAddress) Reset() {
	*x = ProtoAddress{}
	mi := &file_proto_defs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoAddress) ProtoMessage() {}

func (x *ProtoAddress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoAddress.ProtoReflect.Descriptor instead.
func (*ProtoAddress) Descriptor() ([]byte, []int) {
	return file_proto_defs_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoAddress) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProtoLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoLocation) Reset() {
	*x = ProtoLocation{}
	mi := &file_proto_defs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLocation) ProtoMessage() {}

func (x *ProtoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLocation.ProtoReflect.Descriptor instead.
func (*ProtoLocation) Descriptor() ([]byte, []int) {
	return file_proto_defs_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoLocation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Matches ProtoWorkObjectHeader from go-quai
type ProtoWorkObjectHeader struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HeaderHash          *ProtoHash             `protobuf:"bytes,1,opt,name=header_hash,json=headerHash,proto3,oneof" json:"header_hash,omitempty"`
	ParentHash          *ProtoHash             `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3,oneof" json:"parent_hash,omitempty"`
	Number              []byte                 `protobuf:"bytes,3,opt,name=number,proto3,oneof" json:"number,omitempty"`
	Difficulty          []byte                 `protobuf:"bytes,4,opt,name=difficulty,proto3,oneof" json:"difficulty,omitempty"`
	TxHash              *ProtoHash             `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3,oneof" json:"tx_hash,omitempty"`
	Nonce               *uint64                `protobuf:"varint,6,opt,name=nonce,proto3,oneof" json:"nonce,omitempty"`
	Location            *ProtoLocation         `protobuf:"bytes,7,opt,name=location,proto3,oneof" json:"location,omitempty"`
	MixHash             *ProtoHash             `protobuf:"bytes,8,opt,name=mix_hash,json=mixHash,proto3,oneof" json:"mix_hash,omitempty"`
	Time                *uint64                `protobuf:"varint,9,opt,name=time,proto3,oneof" json:"time,omitempty"`
	PrimeTerminusNumber []byte                 `protobuf:"bytes,10,opt,name=prime_terminus_number,json=primeTerminusNumber,proto3,oneof" json:"prime_terminus_number,omitempty"`
	Lock                *uint32                `protobuf:"varint,11,opt,name=lock,proto3,oneof" json:"lock,omitempty"`
	PrimaryCoinbase     *ProtoAddress          `protobuf:"bytes,12,opt,name=primary_coinbase,json=primaryCoinbase,proto3,oneof" json:"primary_coinbase,omitempty"`
	Data                []byte                 `protobuf:"bytes,13,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProtoWorkObjectHeader) Reset() {
	*x = ProtoWorkObjectHeader{}
	mi := &file_proto_defs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoWorkObjectHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoWorkObjectHeader) ProtoMessage() {}

func (x *ProtoWorkObjectHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoWorkObjectHeader.ProtoReflect.Descriptor instead.
func (*ProtoWorkObjectHeader) Descriptor() ([]byte, []int) {
	return file_proto_defs_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoWorkObjectHeader) GetHeaderHash() *ProtoHash {
	if x != nil {
		return x.HeaderHash
	}
	return nil
}

func (x *ProtoWorkObjectHeader) GetParentHash() *ProtoHash {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ProtoWorkObjectHeader) GetNumber() []byte {
	if x != nil {
		return x.Number
	}
	return nil
}

func (x *ProtoWorkObjectHeader) GetDifficulty() []byte {
	if x != nil {
		return x.Difficulty
	}
	return nil
}

func (x *ProtoWorkObjectHeader) GetTxHash() *ProtoHash {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *ProtoWorkObjectHeader) GetNonce() uint64 {
	if x != nil && x.Nonce != nil {
		return *x.Nonce
	}
	return 0
}

func (x *ProtoWorkObjectHeader) GetLocation() *ProtoLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *ProtoWorkObjectHeader) GetMixHash() *ProtoHash {
	if x != nil {
		return x.MixHash
	}
	return nil
}

func (x *ProtoWorkObjectHeader) GetTime() uint64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *ProtoWorkObjectHeader) GetPrimeTerminusNumber() []byte {
	if x != nil {
		return x.PrimeTerminusNumber
	}
	return nil
}

func (x *ProtoWorkObjectHeader) GetLock() uint32 {
	if x != nil && x.Lock != nil {
		return *x.Lock
	}
	return 0
}

func (x *ProtoWorkObjectHeader) GetPrimaryCoinbase() *ProtoAddress {
	if x != nil {
		return x.PrimaryCoinbase
	}
	return nil
}

func (x *ProtoWorkObjectHeader) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_defs_proto protoreflect.FileDescriptor

const file_proto_defs_proto_rawDesc = "" +
	"\n" +
	"\x10proto_defs.proto\x12\x04wasm\"!\n" +
	"\tProtoHash\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"$\n" +
	"\fProtoAddress\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"%\n" +
	"\rProtoLocation\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"\xe6\x05\n" +
	"\x15ProtoWorkObjectHeader\x125\n" +
	"\vheader_hash\x18\x01 \x01(\v2\x0f.wasm.ProtoHashH\x00R\n" +
	"headerHash\x88\x01\x01\x125\n" +
	"\vparent_hash\x18\x02 \x01(\v2\x0f.wasm.ProtoHashH\x01R\n" +
	"parentHash\x88\x01\x01\x12\x1b\n" +
	"\x06number\x18\x03 \x01(\fH\x02R\x06number\x88\x01\x01\x12#\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\fH\x03R\n" +
	"difficulty\x88\x01\x01\x12-\n" +
	"\atx_hash\x18\x05 \x01(\v2\x0f.wasm.ProtoHashH\x04R\x06txHash\x88\x01\x01\x12\x19\n" +
	"\x05nonce\x18\x06 \x01(\x04H\x05R\x05nonce\x88\x01\x01\x124\n" +
	"\blocation\x18\a \x01(\v2\x13.wasm.ProtoLocationH\x06R\blocation\x88\x01\x01\x12/\n" +
	"\bmix_hash\x18\b \x01(\v2\x0f.wasm.ProtoHashH\aR\amixHash\x88\x01\x01\x12\x17\n" +
	"\x04time\x18\t \x01(\x04H\bR\x04time\x88\x01\x01\x127\n" +
	"\x15prime_terminus_number\x18\n" +
	" \x01(\fH\tR\x13primeTerminusNumber\x88\x01\x01\x12\x17\n" +
	"\x04lock\x18\v \x01(\rH\n" +
	"R\x04lock\x88\x01\x01\x12B\n" +
	"\x10primary_coinbase\x18\f \x01(\v2\x12.wasm.ProtoAddressH\vR\x0fprimaryCoinbase\x88\x01\x01\x12\x12\n" +
	"\x04data\x18\r \x01(\fR\x04dataB\x0e\n" +
	"\f_header_hashB\x0e\n" +
	"\f_parent_hashB\t\n" +
	"\a_numberB\r\n" +
	"\v_difficultyB\n" +
	"\n" +
	"\b_tx_hashB\b\n" +
	"\x06_nonceB\v\n" +
	"\t_locationB\v\n" +
	"\t_mix_hashB\a\n" +
	"\x05_timeB\x18\n" +
	"\x16_prime_terminus_numberB\a\n" +
	"\x05_lockB\x13\n" +
	"\x11_primary_coinbaseB\tZ\a./;mainb\x06proto3"

var (
	file_proto_defs_proto_rawDescOnce sync.Once
	file_proto_defs_proto_rawDescData []byte
)

func file_proto_defs_proto_rawDescGZIP() []byte {
	file_proto_defs_proto_rawDescOnce.Do(func() {
		file_proto_defs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_defs_proto_rawDesc), len(file_proto_defs_proto_rawDesc)))
	})
	return file_proto_defs_proto_rawDescData
}

var file_proto_defs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_defs_proto_goTypes = []any{
	(*ProtoHash)(nil),             // 0: wasm.ProtoHash
	(*ProtoAddress)(nil),          // 1: wasm.ProtoAddress
	(*ProtoLocation)(nil),         // 2: wasm.ProtoLocation
	(*ProtoWorkObjectHeader)(nil), // 3: wasm.ProtoWorkObjectHeader
}
var file_proto_defs_proto_depIdxs = []int32{
	0, // 0: wasm.ProtoWorkObjectHeader.header_hash:type_name -> wasm.ProtoHash
	0, // 1: wasm.ProtoWorkObjectHeader.parent_hash:type_name -> wasm.ProtoHash
	0, // 2: wasm.ProtoWorkObjectHeader.tx_hash:type_name -> wasm.ProtoHash
	2, // 3: wasm.ProtoWorkObjectHeader.location:type_name -> wasm.ProtoLocation
	0, // 4: wasm.ProtoWorkObjectHeader.mix_hash:type_name -> wasm.ProtoHash
	1, // 5: wasm.ProtoWorkObjectHeader.primary_coinbase:type_name -> wasm.ProtoAddress
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_defs_proto_init() }
func file_proto_defs_proto_init() {
	if File_proto_defs_proto != nil {
		return
	}
	file_proto_defs_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_defs_proto_rawDesc), len(file_proto_defs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_defs_proto_goTypes,
		DependencyIndexes: file_proto_defs_proto_depIdxs,
		MessageInfos:      file_proto_defs_proto_msgTypes,
	}.Build()
	File_proto_defs_proto = out.File
	file_proto_defs_proto_goTypes = nil
	file_proto_defs_proto_depIdxs = nil
}
